// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARq3655tnv_baRhcpeMT9wK8zFeiWOLKs',
    appId: '1:354414893597:web:453d13c17e7316317d04f4',
    messagingSenderId: '354414893597',
    projectId: 'vid-call-mob',
    authDomain: 'vid-call-mob.firebaseapp.com',
    storageBucket: 'vid-call-mob.firebasestorage.app',
    measurementId: 'G-30QWHW5WV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVzZpAZAe_6wBD6TYzfKzLY6LaM56xPMs',
    appId: '1:354414893597:android:d88b716a7561a55d7d04f4',
    messagingSenderId: '354414893597',
    projectId: 'vid-call-mob',
    storageBucket: 'vid-call-mob.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxQzPnZz4GQcz1lnR2IQ9lGxEdvq_6gjw',
    appId: '1:354414893597:ios:411876e8df09d8577d04f4',
    messagingSenderId: '354414893597',
    projectId: 'vid-call-mob',
    storageBucket: 'vid-call-mob.firebasestorage.app',
    iosBundleId: 'com.example.mobcall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxQzPnZz4GQcz1lnR2IQ9lGxEdvq_6gjw',
    appId: '1:354414893597:ios:411876e8df09d8577d04f4',
    messagingSenderId: '354414893597',
    projectId: 'vid-call-mob',
    storageBucket: 'vid-call-mob.firebasestorage.app',
    iosBundleId: 'com.example.mobcall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARq3655tnv_baRhcpeMT9wK8zFeiWOLKs',
    appId: '1:354414893597:web:ca7e8258d8b4f31f7d04f4',
    messagingSenderId: '354414893597',
    projectId: 'vid-call-mob',
    authDomain: 'vid-call-mob.firebaseapp.com',
    storageBucket: 'vid-call-mob.firebasestorage.app',
    measurementId: 'G-K7DWP3VWLM',
  );
}
